//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WoodPainting2.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WoodPainting2.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _114994 {
            get {
                object obj = ResourceManager.GetObject("114994", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _4213426_about_description_help_info_information_notification_115427 {
            get {
                object obj = ResourceManager.GetObject("4213426-about-description-help-info-information-notification_115427", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _90098_200 {
            get {
                object obj = ResourceManager.GetObject("90098-200", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap clear {
            get {
                object obj = ResourceManager.GetObject("clear", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap delete {
            get {
                object obj = ResourceManager.GetObject("delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Fotoram_io {
            get {
                object obj = ResourceManager.GetObject("Fotoram.io", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap free_icon_close_window_6583137 {
            get {
                object obj = ResourceManager.GetObject("free-icon-close-window-6583137", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap free_icon_expand_window_6583139 {
            get {
                object obj = ResourceManager.GetObject("free-icon-expand-window-6583139", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap free_icon_question_sign_25333 {
            get {
                object obj = ResourceManager.GetObject("free-icon-question-sign-25333", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap g2623 {
            get {
                object obj = ResourceManager.GetObject("g2623", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap g8635 {
            get {
                object obj = ResourceManager.GetObject("g8635", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_задача_64 {
            get {
                object obj = ResourceManager.GetObject("icons8-задача-64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_курсор_48 {
            get {
                object obj = ResourceManager.GetObject("icons8-курсор-48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_палитра_64 {
            get {
                object obj = ResourceManager.GetObject("icons8-палитра-64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_свернуть_окно_64 {
            get {
                object obj = ResourceManager.GetObject("icons8-свернуть-окно-64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_стрелка__указывающая_влево_48 {
            get {
                object obj = ResourceManager.GetObject("icons8-стрелка,-указывающая-влево-48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_тест_частично_пройден_50 {
            get {
                object obj = ResourceManager.GetObject("icons8-тест-частично-пройден-50", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap letter {
            get {
                object obj = ResourceManager.GetObject("letter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap m_arkh_field__1___1_ {
            get {
                object obj = ResourceManager.GetObject("m_arkh field (1) (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;font family=&quot;Georgia&quot; &gt;
        ///        &lt;center&gt;&lt;h1&gt;Выбор темы для изучения&lt;/h1&gt;&lt;/center&gt;
        ///    &lt;p style=&quot;text-indent: 25px;&quot; align=&quot;justify&quot;&gt;При запуске приложения перед Вами отображается карта Архангельской области, на которой Вам необходимо выбрать тему, которой будете обучаться. Для этого нужно нажать на флажок на определенном районе (обведены красными кружоч [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string MapForm {
            get {
                return ResourceManager.GetString("MapForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;font family=&quot;Georgia&quot;&gt;
        ///        &lt;center&gt;&lt;h1&gt;Графический редактор&lt;/h1&gt;&lt;/center&gt;
        ///        &lt;p style=&quot;text-indent: 25px;&quot; align=&quot;justify&quot;&gt;При переходе к графическому редактору перед Вами появляется окно, на котором расположены панели с инструментами и панели с шаблонами для каждой темы.&lt;/p&gt;
        ///        &lt;p style=&quot;text-indent: 25px;&quot; align=&quot;justify&quot;&gt;Если Вы хотите [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string PaintingForm {
            get {
                return ResourceManager.GetString("PaintingForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap palete {
            get {
                object obj = ResourceManager.GetObject("palete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap panel {
            get {
                object obj = ResourceManager.GetObject("panel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pen2 {
            get {
                object obj = ResourceManager.GetObject("pen2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap premium_icon_move_button_4674048 {
            get {
                object obj = ResourceManager.GetObject("premium-icon-move-button-4674048", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap premium_icon_question_3156235 {
            get {
                object obj = ResourceManager.GetObject("premium-icon-question-3156235", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;font family=&quot;Georgia&quot; &gt;
        ///        &lt;center&gt;&lt;h1&gt;Тестирование&lt;/h1&gt;&lt;/center&gt;
        ///    &lt;p style=&quot;text-indent: 25px;&quot; align=&quot;justify&quot;&gt;При переходе к тестированию перед Вами появляется окно, на котором сначала необходимо изучить информацию о тестировании, затем нажать на кнопку &quot;Далее&quot;.&lt;/p&gt;
        ///    &lt;p style=&quot;text-indent: 25px;&quot; align=&quot;justify&quot;&gt;В левом верхнем углу напис [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string QuestionsForm {
            get {
                return ResourceManager.GetString("QuestionsForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rect {
            get {
                object obj = ResourceManager.GetObject("rect", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap round {
            get {
                object obj = ResourceManager.GetObject("round", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;font family=&quot;Georgia&quot; &gt;
        ///        &lt;center&gt;&lt;h1&gt;Практические упражнения&lt;/h1&gt;&lt;/center&gt;
        ///    &lt;p style=&quot;text-indent: 25px;&quot; align=&quot;justify&quot;&gt;При переходе к практической части изучения темы перед Вами появляется окно, где Вы можете закрепить полученные знания с помощью двух простых упражнений.&lt;/p&gt;
        ///    &lt;p style=&quot;text-indent: 25px;&quot; align=&quot;justify&quot;&gt;В левой части о [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string TasksForm {
            get {
                return ResourceManager.GetString("TasksForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;font family=&quot;Georgia&quot; &gt;
        ///        &lt;center&gt;&lt;h1&gt;Изучение теоретического материала&lt;/h1&gt;&lt;/center&gt;
        ///    &lt;p style=&quot;text-indent: 25px;&quot; align=&quot;justify&quot;&gt;После выбора темы открывается окно, где можно изучить теоретический материал. &lt;/p&gt;
        ///    &lt;p style=&quot;text-indent: 25px;&quot; align=&quot;justify&quot;&gt;Теоретический материал разбит на подпункты для удобства изучения темы. Слева на [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string TheoryForm {
            get {
                return ResourceManager.GetString("TheoryForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap triangle {
            get {
                object obj = ResourceManager.GetObject("triangle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;div id=&quot;History&quot; align=&quot;justify&quot;&gt;
        ///        &lt;center&gt;&lt;h1&gt;История Борецкой росписи&lt;/h1&gt;&lt;/center&gt;
        ///        &lt;p style=&quot;text-indent: 25px;&quot; align=&quot;justify&quot;&gt;Борецкая роспись - одна из разновидностей северорусской графической росписи, наряду с такими, например, как пермогорская или мезенская.&lt;/p&gt;
        ///        &lt;p style=&quot;text-indent: 25px;&quot; align=&quot;justify&quot;&gt;Борок - древнее [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Борецкая_роспись_История {
            get {
                return ResourceManager.GetString("Борецкая роспись История", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;div allign=&quot;justify&quot;&gt;
        ///        &lt;font font-family=&quot;Times&quot; size=&quot;4&quot;&gt; 
        ///            &lt;center&gt;&lt;h1&gt;Композиции Борецкой росписи&lt;/h1&gt;&lt;/center&gt;
        ///            &lt;p style=&quot;text-indent: 25px;&quot; align=&quot;justify&quot;&gt;&lt;strong&gt;1. Прялка. Вторая половина XIX века (Архангельская область. Виноградовский район. Пристань Борок. Деревня Скобели.) &lt;/strong&gt;&lt;/p&gt;
        ///            &lt;center&gt;&lt;img s [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Борецкая_роспись_Композиции {
            get {
                return ResourceManager.GetString("Борецкая роспись Композиции", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;div allign=&quot;justify&quot;&gt;
        ///        &lt;center&gt;&lt;h1&gt;Мастера Борецкой росписи&lt;/h1&gt;&lt;/center&gt;
        ///        &lt;p style=&quot;text-indent: 25px;&quot; align=&quot;justify&quot;&gt;В деревне Скобели, возле пристани Борок, жила Пелагея Матвеевна Амосова, по прозвищу Польникова. Её работы по росписи прялок широко известны. Живописцами были и её братья Степан, Никифор, Василий, Михаил, Кузьма, но на баз [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Борецкая_роспись_Мастера {
            get {
                return ResourceManager.GetString("Борецкая роспись Мастера", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;div id=&quot;History&quot; align=&quot;justify&quot;&gt;
        ///        &lt;center&gt;&lt;h1&gt;Борецкая роспись в наше время&lt;/h1&gt;&lt;/center&gt;
        ///        &lt;p style=&quot;text-indent: 25px;&quot; align=&quot;justify&quot;&gt;В настоящее время в Архангельске и области при центрах народных промыслов существуют мастерские с учебными классами подготовки юных мастеров. В Архангельске работает ряд кружков и студий по народным промыс [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Борецкая_роспись_Сейчас {
            get {
                return ResourceManager.GetString("Борецкая роспись Сейчас", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;div id=&quot;Symbols&quot; allign=&quot;justify&quot;&gt;
        ///        &lt;font font-family=&quot;Times&quot; size=&quot;4&quot;&gt; &lt;center&gt;&lt;h1&gt;Элементы Борецкой росписи:&lt;/h1&gt;&lt;/center&gt;
        ///        &lt;p style=&quot;text-indent: 25px;&quot; align=&quot;justify&quot;&gt;Наиболее часто используемые цвета в росписи: красный, зеленый, коричневый, оранжевый, желтый. Редко - синий. Орнамент состоит из ромбиков, кружочков, капелек, треугольни [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Борецкая_роспись_Элементы {
            get {
                return ResourceManager.GetString("Борецкая роспись Элементы", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Заставка {
            get {
                object obj = ResourceManager.GetObject("Заставка", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;div id=&quot;History&quot; align=&quot;justify&quot;&gt;
        ///        &lt;p style=&quot;text-indent: 25px;&quot; align=&quot;justify&quot;&gt;Мезенская роспись возникла в начале XIX века в низовьях реки Мезень Архангельской области. Ею расписывали различную домашнюю утварь — прялки, ковши, короба, сундуки, шкатулки. С конца XIX века центром мезенской росписи становится деревня Палащелье, поэтому мезенская р [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Мезенская_роспись_История {
            get {
                return ResourceManager.GetString("Мезенская роспись История", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;div align=&quot;justify&quot;&gt;
        ///        &lt;font font-family=&quot;Times&quot; size=&quot;4&quot;&gt; &lt;center&gt;&lt;h1&gt;Композиции Мезенской росписи:&lt;/h1&gt;&lt;/center&gt;
        ///        &lt;p style=&quot;text-indent: 25px;&quot; align=&quot;justify&quot;&gt;Много всякой всячины расписывали палащельские мастера: ложки, солоницы, коробейки для хлеба и предметов рукоделия, сосуды для напитков и, конечно же, прялки.&lt;/p&gt;
        ///        &lt;p style= [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Мезенская_роспись_Композиции {
            get {
                return ResourceManager.GetString("Мезенская роспись Композиции", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;div align=&quot;justify&quot;&gt;
        ///        &lt;font font-family=&quot;Times&quot; size=&quot;4&quot;&gt; &lt;center&gt;&lt;h1&gt;Мастера Мезенской росписи:&lt;/h1&gt;&lt;/center&gt;
        ///        &lt;p style=&quot;text-indent: 25px;&quot; align=&quot;justify&quot;&gt;Мастерством росписи в Палощелье славились пять фамилий: Аксеновы, Новиковы, Шишовы, Федотовы и Кузьмины. Мезенская прялка называлась по-местному прялицей-кокорицей или корневухой. Наз [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Мезенская_роспись_Мастера {
            get {
                return ResourceManager.GetString("Мезенская роспись Мастера", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;div align=&quot;justify&quot;&gt;
        ///        &lt;font font-family=&quot;Times&quot; size=&quot;4&quot;&gt; &lt;center&gt;&lt;h1&gt;Современное состояние мезенской росписи&lt;/h1&gt;&lt;/center&gt;
        ///        &lt;p style=&quot;text-indent: 25px;&quot; align=&quot;justify&quot;&gt;В Северодвинске, Архангельске и других местах сейчас широко развернуто производство сувениров в мезенском стиле. Роспись хороша, но характер ее уже несколько иной, уходит [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Мезенская_роспись_Сейчас {
            get {
                return ResourceManager.GetString("Мезенская роспись Сейчас", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;div align=&quot;justify&quot;&gt;
        ///        &lt;font font-family=&quot;Times&quot; size=&quot;4&quot;&gt; &lt;center&gt;&lt;h1&gt;Элементы Мезенской росписи:&lt;/h1&gt;&lt;/center&gt;
        ///        &lt;p style=&quot;text-indent: 25px;&quot; align=&quot;justify&quot;&gt;&lt;strong&gt;1. РИСОВАНИЕ ЭЛЕМЕНТОВ МЕЗЕНСКОЙ РОСПИСИ &lt;/strong&gt;&lt;/p&gt;
        ///        &lt;p style=&quot;text-indent: 25px;&quot; align=&quot;justify&quot;&gt;Начать изучение мезенской росписи лучше всего с освоения простей [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Мезенская_роспись_Элементы {
            get {
                return ResourceManager.GetString("Мезенская роспись Элементы", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Нет_фото {
            get {
                object obj = ResourceManager.GetObject("Нет_фото", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Нет_фото_маленькая {
            get {
                object obj = ResourceManager.GetObject("Нет_фото_маленькая", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Нет_фото_средняя {
            get {
                object obj = ResourceManager.GetObject("Нет_фото_средняя", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;div align=&quot;justify&quot;&gt;
        ///        &lt;p style=&quot;text-indent: 25px;&quot; align=&quot;justify&quot;&gt;Онежская роспись возникла в конце 18 века и бытовала в нижнем течении реки Онеги. Судя по прялке 1879 года из Посадской волости Онежского уезда Архангельской губернии, онежские прялки - около 90 см в высоту, но более изящные, чем каргопольские.&lt;/p&gt;
        ///        &lt;p style=&quot;text-indent:  [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Онежская_роспись_История {
            get {
                return ResourceManager.GetString("Онежская роспись История", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;div align=&quot;justify&quot;&gt;
        ///        &lt;font font-family=&quot;Times&quot; size=&quot;4&quot;&gt; &lt;center&gt;&lt;h1&gt;Композиции Онежской росписи&lt;/h1&gt;&lt;/center&gt;
        ///        &lt;p style=&quot;text-indent: 25px;&quot; align=&quot;justify&quot;&gt;&lt;strong&gt;Онежские прялки&lt;/strong&gt;
        ///        &lt;p style=&quot;text-indent: 25px;&quot; align=&quot;justify&quot;&gt;Лопастка прялки — узкая, вытянутая, прямоугольная (90х19х85), со скругленными углами. Части ст [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Онежская_роспись_Композиции {
            get {
                return ResourceManager.GetString("Онежская роспись Композиции", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;div align=&quot;justify&quot;&gt;
        ///        &lt;font font-family=&quot;Times&quot; size=&quot;4&quot;&gt; &lt;center&gt;&lt;h1&gt;Мастера Онежской росписи&lt;/h1&gt;&lt;/center&gt;
        ///            &lt;p style=&quot;text-indent: 25px;&quot; align=&quot;justify&quot;&gt;С культом растительности, отразившемся на народном творчестве, издавна было связано украшение дома, одежды крестьянина. Человек, в стремлении к искусству, становился мастером и толь [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Онежская_роспись_Мастера {
            get {
                return ResourceManager.GetString("Онежская роспись Мастера", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;div align=&quot;justify&quot;&gt;
        ///        &lt;font font-family=&quot;Times&quot; size=&quot;4&quot;&gt;
        ///            &lt;center&gt;&lt;h1&gt;Онежская роспись сейчас&lt;/h1&gt;&lt;/center&gt;
        ///            &lt;p style=&quot;text-indent: 25px;&quot; align=&quot;justify&quot;&gt;Сейчас роосписью занимается фабрика &quot;Беломорские узоры&quot;.&lt;/p&gt;
        ///            &lt;center&gt;&lt;img src=&quot;Беломорские узоры.png&quot; /&gt;&lt;/center&gt;
        ///            &lt;p style=&quot;text-indent: 25px;&quot; [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Онежская_роспись_Сейчас {
            get {
                return ResourceManager.GetString("Онежская роспись Сейчас", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;div align=&quot;justify&quot;&gt;
        ///        &lt;font font-family=&quot;Times&quot; size=&quot;4&quot;&gt;
        ///            &lt;center&gt;&lt;h1&gt;Элементы Онежской росписи:&lt;/h1&gt;&lt;/center&gt;
        ///            &lt;p style=&quot;text-indent: 25px;&quot; align=&quot;justify&quot;&gt;Для фона Онежской росписи характерен голубой, коричневый и тёмно-зелёный цвет фона. Цветовая гамма элементов – красный, белый, зелёный, жёлтый цвета, чёрная оживка.&lt;/ [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Онежская_роспись_Элементы {
            get {
                return ResourceManager.GetString("Онежская роспись Элементы", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;div align=&quot;justify&quot;&gt;
        ///        &lt;font font-family=&quot;Times&quot; size=&quot;4&quot;&gt; &lt;center&gt;&lt;h1&gt;История Пермогорской росписи:&lt;/h1&gt;&lt;/center&gt;
        ///        &lt;p style=&quot;text-indent: 25px;&quot; align=&quot;justify&quot;&gt;Возникновение промысла, прославившего не просто свой регион, но и русское декоративно-прикладное искусство за пределами страны, связано с 13-ым столетием. Пермогорьем называют прис [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Пермогорская_роспись_История {
            get {
                return ResourceManager.GetString("Пермогорская роспись История", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;div align=&quot;justify&quot;&gt;
        ///        &lt;font font-family=&quot;Times&quot; size=&quot;4&quot;&gt; &lt;center&gt;&lt;h1&gt;Композиции Пермогорской росписи:&lt;/h1&gt;&lt;/center&gt;
        ///        &lt;p style=&quot;text-indent: 25px;&quot; align=&quot;justify&quot;&gt;&lt;strong&gt;1. ПЕРМОГОРСКИЕ ПРЯЛКИ&lt;/strong&gt;&lt;/p&gt;
        ///        &lt;center&gt;&lt;img src=&quot;Строекние прялки.png&quot; /&gt;&lt;/center&gt;
        ///        &lt;p style=&quot;text-indent: 25px;&quot; align=&quot;justify&quot;&gt;Техника исполнени [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Пермогорская_роспись_Композиции {
            get {
                return ResourceManager.GetString("Пермогорская роспись Композиции", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;div align=&quot;justify&quot;&gt;
        ///        &lt;font font-family=&quot;Times&quot; size=&quot;4&quot;&gt; &lt;center&gt;&lt;h1&gt;Мастера Пермогорской росписи:&lt;/h1&gt;&lt;/center&gt;
        ///        &lt;p style=&quot;text-indent: 25px;&quot; align=&quot;justify&quot;&gt;Известные мастера, прославившие пермогорскую роспись на весь мир — династия Ярыгиных, Хрипуновых и Хвостовых.&lt;/p&gt;
        ///        &lt;p style=&quot;text-indent: 25px;&quot; align=&quot;justify&quot;&gt;Один из сам [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Пермогорская_роспись_Мастера {
            get {
                return ResourceManager.GetString("Пермогорская роспись Мастера", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;div align=&quot;justify&quot;&gt;
        ///        &lt;font font-family=&quot;Times&quot; size=&quot;4&quot;&gt; &lt;center&gt;&lt;h1&gt;Пермогорская роспись сейчас&lt;/h1&gt;&lt;/center&gt;
        ///        &lt;p style=&quot;text-indent: 25px;&quot; align=&quot;justify&quot;&gt;Шторы с росписью, скатерти, предметы утвари отлично впишутся в интерьер! На кухне главную роль будет играть, конечно же, посуда. Небольшие плошки и огромные блюда, разделочные доски  [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Пермогорская_роспись_Сейчас {
            get {
                return ResourceManager.GetString("Пермогорская роспись Сейчас", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;div align=&quot;justify&quot;&gt;
        ///        &lt;font font-family=&quot;Times&quot; size=&quot;4&quot;&gt; &lt;center&gt;&lt;h1&gt;Элементы Пермогорской росписи:&lt;/h1&gt;&lt;/center&gt;
        ///        &lt;p style=&quot;text-indent: 25px;&quot; align=&quot;justify&quot;&gt;Красный, желтый, зеленый – это основные цвета пермогорской росписи. Они часто чередуются вследствие более мелкого рисунка и дробных участков расцветки. Этой росписи характерны кра [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Пермогорская_роспись_Элементы {
            get {
                return ResourceManager.GetString("Пермогорская роспись Элементы", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;div align=&quot;justify&quot;&gt;
        ///        &lt;font font-family=&quot;Times&quot; size=&quot;4&quot;&gt; &lt;center&gt;&lt;h1&gt;История Пижемской росписи:&lt;/h1&gt;&lt;/center&gt;
        ///        &lt;p style=&quot;text-indent: 25px;&quot; align=&quot;justify&quot;&gt;Одна из древнейших росписей Русского севера, известная с 17 века. Центром графической росписи стала северная речка Печора, а также ее притоки Цильма и Пижма (отсюда и название промысл [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Пижемская_роспись_История {
            get {
                return ResourceManager.GetString("Пижемская роспись История", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;div id=&quot;History&quot; align=&quot;justify&quot;&gt;
        ///        &lt;font font-family=&quot;Times&quot; size=&quot;4&quot;&gt; &lt;center&gt;&lt;h1&gt;Композиции Пижемской росписи:&lt;/h1&gt;&lt;/center&gt;
        ///        &lt;p style=&quot;text-indent: 25px;&quot; align=&quot;justify&quot;&gt;Мотивы пижемской росписи образуют различные композиции в зависимости от назначения предмета. &lt;/p&gt;
        ///        &lt;p style=&quot;text-indent: 25px;&quot; align=&quot;justify&quot;&gt;В целом композ [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Пижемская_роспись_Композиции {
            get {
                return ResourceManager.GetString("Пижемская роспись Композиции", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;div id=&quot;History&quot; align=&quot;justify&quot;&gt;
        ///        &lt;font font-family=&quot;Times&quot; size=&quot;4&quot;&gt; &lt;center&gt;&lt;h1&gt;Мастера Пижемской росписи:&lt;/h1&gt;&lt;/center&gt;
        ///        &lt;p style=&quot;text-indent: 25px;&quot; align=&quot;justify&quot;&gt;Мастерами этой росписи были: И. С. Мяндин, П. А. Мяндин, С. И. Мяндин, Н. И. Носов, Ф. С. Бобрецов, А. А. Вакуев, А. М. Бажуков, О. С. Аншуков, С. С. Чупров.&lt;/p&gt;
        ///        [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Пижемская_роспись_Мастера {
            get {
                return ResourceManager.GetString("Пижемская роспись Мастера", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;div id=&quot;History&quot; align=&quot;justify&quot;&gt;
        ///        &lt;font font-family=&quot;Times&quot; size=&quot;4&quot;&gt; &lt;center&gt;&lt;h1&gt;Пижемская роспись сейчас:&lt;/h1&gt;&lt;/center&gt;
        ///        &lt;p style=&quot;text-indent: 25px;&quot; align=&quot;justify&quot;&gt;Традиции пижемской росписи сохраняются по сей день. В селах Усть-Цилемского района Республики Коми, где зародился промысел, предметы с пижемской росписью можно встретить в [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Пижемская_роспись_Сейчас {
            get {
                return ResourceManager.GetString("Пижемская роспись Сейчас", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;div id=&quot;History&quot; align=&quot;justify&quot;&gt;
        ///        &lt;font font-family=&quot;Times&quot; size=&quot;4&quot;&gt; &lt;center&gt;&lt;h1&gt;Элементы Пижемской росписи:&lt;/h1&gt;&lt;/center&gt;
        ///        &lt;p style=&quot;text-indent: 25px;&quot; align=&quot;justify&quot;&gt;&lt;strong&gt;1. Небесная и земная твердь&lt;/strong&gt;&lt;/p&gt;
        ///        &lt;p style=&quot;text-indent: 25px;&quot; align=&quot;justify&quot;&gt;Прямая линия может обозначать твердь небесную и твердь земную.&lt;/p [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Пижемская_роспись_Элементы {
            get {
                return ResourceManager.GetString("Пижемская роспись Элементы", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;div align=&quot;justify&quot;&gt;
        ///        &lt;font font-family=&quot;Times&quot; size=&quot;4&quot;&gt; &lt;center&gt;&lt;h1&gt;История Пучужской росписи:&lt;/h1&gt;&lt;/center&gt;
        ///        &lt;p style=&quot;text-indent: 25px;&quot; align=&quot;justify&quot;&gt;Этот вид росписи берет свое начало в селе Пучуга, которое расположено на реке Двина Архангельской области. Осевшие поляки и старообрядцы активно занимались переписью и написанием книг [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Пучужская_роспись_История {
            get {
                return ResourceManager.GetString("Пучужская роспись История", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;div id=&quot;History&quot; align=&quot;justify&quot;&gt;
        ///        &lt;font font-family=&quot;Times&quot; size=&quot;4&quot;&gt; &lt;center&gt;&lt;h1&gt;Композиции Пучужской росписи:&lt;/h1&gt;&lt;/center&gt;
        ///        &lt;p style=&quot;text-indent: 25px;&quot; align=&quot;justify&quot;&gt;Основными мотивами композиции служат жанровые сцены катания на лошадях. В красную кудрявую листву мастера любили вплетать красных птиц.&lt;/p&gt;
        ///        &lt;p style=&quot;text-ind [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Пучужская_роспись_Композиции {
            get {
                return ResourceManager.GetString("Пучужская роспись Композиции", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;div align=&quot;justify&quot;&gt;
        ///        &lt;font font-family=&quot;Times&quot; size=&quot;4&quot;&gt; &lt;center&gt;&lt;h1&gt;Мастера Пучужской росписи:&lt;/h1&gt;&lt;/center&gt;
        ///        &lt;p style=&quot;text-indent: 25px;&quot; align=&quot;justify&quot;&gt;Мастера расписывали предметы домашней утвари, сохранилась роспись, в основном, на прялках. &lt;/p&gt;
        ///        &lt;p style=&quot;text-indent: 25px;&quot; align=&quot;justify&quot;&gt;Представители пучужской прялочно [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Пучужская_роспись_Мастера {
            get {
                return ResourceManager.GetString("Пучужская роспись Мастера", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;div align=&quot;justify&quot;&gt;
        ///        &lt;font font-family=&quot;Times&quot; size=&quot;4&quot;&gt; &lt;center&gt;&lt;h1&gt;Пучужская роспись сейчас:&lt;/h1&gt;&lt;/center&gt;
        ///        &lt;p style=&quot;text-indent: 25px;&quot; align=&quot;justify&quot;&gt;С 1995 года в Пучуге работал филиал областной Школы народных ремесел. Руководителем мастерской по росписи была Шумкова Тамара Викторовна. Она учила ребят не забывать прошлое, возрождат [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Пучужская_роспись_Сейчас {
            get {
                return ResourceManager.GetString("Пучужская роспись Сейчас", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;div align=&quot;justify&quot;&gt;
        ///        &lt;font font-family=&quot;Times&quot; size=&quot;4&quot;&gt; &lt;center&gt;&lt;h1&gt;Элементы Пучужской росписи:&lt;/h1&gt;&lt;/center&gt;
        ///        &lt;p style=&quot;text-indent: 25px;&quot; align=&quot;justify&quot;&gt;Пучужская роспись выполняется на белом фоне красной краской, украшается ярко-зелеными листочками и белыми точками - капельками. В некоторых изделиях встречается синий цвет. &lt;/p&gt;
        ///    [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Пучужская_роспись_Элементы {
            get {
                return ResourceManager.GetString("Пучужская роспись Элементы", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;div align=&quot;justify&quot;&gt;
        ///        &lt;font font-family=&quot;Times&quot; size=&quot;4&quot;&gt; &lt;center&gt;&lt;h1&gt;История Ракульской росписи&lt;/h1&gt;&lt;/center&gt;
        ///        &lt;p style=&quot;text-indent: 25px;&quot; align=&quot;justify&quot;&gt;Ракулкой в Красноборском районе Архангельской области называют два куста деревень на правом берегу Северной Двины (Верхняя Ракулка и Нижняя Ракулка), в семи километрах ниже по течению [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Ракульская_роспись_История {
            get {
                return ResourceManager.GetString("Ракульская роспись История", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;div allign=&quot;justify&quot;&gt;
        ///        &lt;font font-family=&quot;Times&quot; size=&quot;4&quot;&gt; &lt;center&gt;&lt;h1&gt;Композиции Ракульской росписи:&lt;/h1&gt;&lt;/center&gt;
        ///        &lt;p style=&quot;text-indent: 25px;&quot; align=&quot;justify&quot;&gt;Роспись ракульской прялки строится по четкой схеме. Фасадная переходящее в лопасть, - заполнялась вертикальной веткой с крупными, симметрично расположенными листьями и черными ус [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Ракульская_роспись_Композиции {
            get {
                return ResourceManager.GetString("Ракульская роспись Композиции", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;div align=&quot;justify&quot;&gt;
        ///        &lt;font font-family=&quot;Times&quot; size=&quot;4&quot;&gt; &lt;center&gt;&lt;h1&gt;Мастера Ракульской росписи&lt;/h1&gt;&lt;/center&gt;
        ///        &lt;p style=&quot;text-indent: 25px;&quot; align=&quot;justify&quot;&gt;Наиболее глубоким изучением ракульской росписи занимались известные исследователи народного искусства О.В. Круглова, Н.В. Тарановская, М.Д. Урюпина, О.В. Алексеева.&lt;/p&gt;
        ///        &lt;p st [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Ракульская_роспись_Мастера {
            get {
                return ResourceManager.GetString("Ракульская роспись Мастера", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;div align=&quot;justify&quot;&gt;
        ///        &lt;font font-family=&quot;Times&quot; size=&quot;4&quot;&gt; &lt;center&gt;&lt;h1&gt;Ракульская роспись сейчас&lt;/h1&gt;&lt;/center&gt;
        ///        &lt;p style=&quot;text-indent: 25px;&quot; align=&quot;justify&quot;&gt;Ракульская роспись довольно интенсивно развивается сегодня, однако неспециалисты искажают эту роспись, а специалисты наоборот же создают современные шедевры.&lt;/p&gt;
        ///        &lt;center&gt;&lt;img  [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Ракульская_роспись_Сейчас {
            get {
                return ResourceManager.GetString("Ракульская роспись Сейчас", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;div id=&quot;Symbols&quot; allign=&quot;justify&quot;&gt;
        ///        &lt;font font-family=&quot;Times&quot; size=&quot;4&quot;&gt; &lt;center&gt;&lt;h1&gt;Элементы Ракульской росписи:&lt;/h1&gt;&lt;/center&gt;
        ///        &lt;p style=&quot;text-indent: 25px;&quot; align=&quot;justify&quot;&gt;В большинстве произведений Ракульской росписи главную роль играют золотисто-охристый и черный цвета, а сопутствуют им чаще всего глубокий зеленый и коричнево-красный.  [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Ракульская_роспись_Элементы {
            get {
                return ResourceManager.GetString("Ракульская роспись Элементы", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap растровый {
            get {
                object obj = ResourceManager.GetObject("растровый", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Сюжет4 {
            get {
                object obj = ResourceManager.GetObject("Сюжет4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;div align=&quot;justify&quot;&gt;
        ///        &lt;font font-family=&quot;Times&quot; size=&quot;4&quot;&gt; &lt;center&gt;&lt;h1&gt;История Уфтюжской росписи:&lt;/h1&gt;&lt;/center&gt;
        ///        &lt;p style=&quot;text-indent: 25px;&quot; align=&quot;justify&quot;&gt;&quot;Верхняя Уфтюга (в местном наречии &quot;Ухтюга&quot;) — село, названное именем реки — небольшого притока Северной Двины, пересыхающего летом. &quot;Ниже устья Вычегды с правой стороны тридцать верс [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Уфтюжская_роспись_История {
            get {
                return ResourceManager.GetString("Уфтюжская роспись История", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;div align=&quot;justify&quot;&gt;
        ///        &lt;font font-family=&quot;Times&quot; size=&quot;4&quot;&gt; &lt;center&gt;&lt;h1&gt;Композиции Уфтюжской росписи&lt;/h1&gt;&lt;/center&gt;
        ///        &lt;p style=&quot;text-indent: 25px;&quot; align=&quot;justify&quot;&gt;Композиция росписи всегда одна и та же — это гибкая веточка, несущая легкий цветок (тюльпаны-лилии, &quot;котлы&quot;, &quot;лунники&quot;, репей, ромашки), раскинувшиеся опущенные ресничками листья, н [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Уфтюжская_роспись_Композиции {
            get {
                return ResourceManager.GetString("Уфтюжская роспись Композиции", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;div align=&quot;justify&quot;&gt;
        ///        &lt;font font-family=&quot;Times&quot; size=&quot;4&quot;&gt; &lt;center&gt;&lt;h1&gt;Мастера Уфтюжской росписи&lt;/h1&gt;&lt;/center&gt;
        ///        &lt;p style=&quot;text-indent: 25px;&quot; align=&quot;justify&quot;&gt;Один из известных мастеров - Бестужев Ф. И. В его росписи заметно стремление к динамичности композиции, к усилению роли контура, контрастности. Интересны птицы на туесах Бестужева: одн [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Уфтюжская_роспись_Мастера {
            get {
                return ResourceManager.GetString("Уфтюжская роспись Мастера", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;div align=&quot;justify&quot;&gt;
        ///        &lt;font font-family=&quot;Times&quot; size=&quot;4&quot;&gt; &lt;center&gt;&lt;h1&gt;Уфтюжская роспись сейчас:&lt;/h1&gt;&lt;/center&gt;
        ///        &lt;p style=&quot;text-indent: 25px;&quot; align=&quot;justify&quot;&gt;Предметы, расписанные уфтюжской росписи, хранятся в музеях.&lt;/p&gt;
        ///        &lt;center&gt;&lt;img src=&quot;Туеса в музее.jpg&quot; /&gt;&lt;/center&gt;
        ///        &lt;p style=&quot;text-indent: 25px;&quot; align=&quot;justify&quot;&gt;В наше  [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Уфтюжская_роспись_Сейчас {
            get {
                return ResourceManager.GetString("Уфтюжская роспись Сейчас", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;div id=&quot;History&quot; align=&quot;justify&quot;&gt;
        ///        &lt;font font-family=&quot;Times&quot; size=&quot;4&quot;&gt; &lt;center&gt;&lt;h1&gt;Элементы Уфтюжской росписи&lt;/h1&gt;&lt;/center&gt;
        ///        &lt;p style=&quot;text-indent: 25px;&quot; align=&quot;justify&quot;&gt;&lt;strong&gt;ПОСЛЕДОВАТЕЛЬНОСТЬ ИСПОЛЬЗОВАНИЯ КРАСОК В РОСПИСИ&lt;/strong&gt;&lt;/p&gt;
        ///        &lt;center&gt;&lt;img src=&quot;Краски.png&quot; /&gt;&lt;/center&gt;
        ///        &lt;p style=&quot;text-indent: 25px;&quot; align=&quot;ju [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Уфтюжская_роспись_Элементы {
            get {
                return ResourceManager.GetString("Уфтюжская роспись Элементы", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Флажок {
            get {
                object obj = ResourceManager.GetObject("Флажок", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Фон {
            get {
                object obj = ResourceManager.GetObject("Фон", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;div align=&quot;justify&quot;&gt;
        ///        &lt;font font-family=&quot;Times&quot; size=&quot;4&quot;&gt; &lt;center&gt;&lt;h1&gt;История Шенкурской росписи&lt;/h1&gt;&lt;/center&gt;
        ///        &lt;p style=&quot;text-indent: 25px;&quot; align=&quot;justify&quot;&gt;Шенкурская роспись была распространена по всему течению реки Ваги, левого притока Северной Двины. По своей композиции, орнаменту, цветовой гамме она значительно отличается от других с [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Шенкурская_роспись_История {
            get {
                return ResourceManager.GetString("Шенкурская роспись История", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;div align=&quot;justify&quot;&gt;
        ///        &lt;font font-family=&quot;Times&quot; size=&quot;4&quot;&gt; &lt;center&gt;&lt;h1&gt;Композиции Шенкурской росписи&lt;/h1&gt;&lt;/center&gt;
        ///        &lt;p style=&quot;text-indent: 25px;&quot; align=&quot;justify&quot;&gt;В основе рисунка - три крупных цветка, нанесенных по центральной оси лопасти один над другим. &lt;/p&gt;
        ///        &lt;p style=&quot;text-indent: 25px;&quot; align=&quot;justify&quot;&gt;Данная роспись относится к [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Шенкурская_роспись_Композиции {
            get {
                return ResourceManager.GetString("Шенкурская роспись Композиции", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;div align=&quot;justify&quot;&gt;
        ///        &lt;font font-family=&quot;Times&quot; size=&quot;4&quot;&gt; &lt;center&gt;&lt;h1&gt;Мастера Шенкурской росписи&lt;/h1&gt;&lt;/center&gt;
        ///        &lt;p style=&quot;text-indent: 25px;&quot; align=&quot;justify&quot;&gt;Мастерами росписи были члены семей Ульяновских, Козьма Дмитриев, Семен Иванов, Никита Трофимов, Иван Васильевич Кутышев (д. Келгозеро, ныне — Федотовская), Федор Иванович Раков (г. Ше [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Шенкурская_роспись_Мастера {
            get {
                return ResourceManager.GetString("Шенкурская роспись Мастера", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;div align=&quot;justify&quot;&gt;
        ///        &lt;font font-family=&quot;Times&quot; size=&quot;4&quot;&gt; &lt;center&gt;&lt;h1&gt;Шенкурская роспись сейчас:&lt;/h1&gt;&lt;/center&gt;
        ///        &lt;p style=&quot;text-indent: 25px;&quot; align=&quot;justify&quot;&gt;Сегодня, мастера и бывшие ученики шенкурской детской художественной школы продолжают дело шенкурских «маляров» второй половины XIX – начала XX вв., ищут новые решения, приемы и объект [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Шенкурская_роспись_Сейчас {
            get {
                return ResourceManager.GetString("Шенкурская роспись Сейчас", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;div align=&quot;justify&quot;&gt;
        ///        &lt;font font-family=&quot;Times&quot; size=&quot;4&quot;&gt; &lt;center&gt;&lt;h1&gt;Элементы Шенкурской росписи&lt;/h1&gt;&lt;/center&gt;
        ///        &lt;p style=&quot;text-indent: 25px;&quot; align=&quot;justify&quot;&gt;Для шенкурской росписи характерен оранжевый, красный фон, встречается охристо -желтый, изумрудно-зеленый, темно-синий. Цветовая гамма росписи - насыщенная, преобладают красноватые, о [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Шенкурская_роспись_Элементы {
            get {
                return ResourceManager.GetString("Шенкурская роспись Элементы", resourceCulture);
            }
        }
    }
}
